-- =============================================================================
-- 02_corporativo.sql — Estrutura organizacional
-- =============================================================================
-- Tabelas de cardinalidade baixa (dezenas a centenas de linhas) e mudança lenta.
-- No Data Lake são carga full diária; no Warehouse viram dimensões.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- unidades
-- -----------------------------------------------------------------------------
CREATE TABLE erp.unidades (
    unidade_id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_unidade      VARCHAR(10)  NOT NULL UNIQUE,
    nome_unidade        VARCHAR(120) NOT NULL,
    cidade              VARCHAR(80)  NOT NULL,
    uf                  erp.uf_br    NOT NULL,
    regiao              VARCHAR(20)  NOT NULL,
    cnpj                VARCHAR(18)  NOT NULL UNIQUE,
    data_inauguracao    DATE         NOT NULL,
    qtd_consultorios    SMALLINT     NOT NULL CHECK (qtd_consultorios > 0),
    horario_abertura    TIME         NOT NULL DEFAULT '08:00',
    horario_fechamento  TIME         NOT NULL DEFAULT '19:00',
    ativa               BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  erp.unidades IS 'Clínicas físicas da rede.';
COMMENT ON COLUMN erp.unidades.codigo_unidade IS
    'Chave natural do ERP (ex.: SP01). Sobrevive a migração de banco; o unidade_id não.';
COMMENT ON COLUMN erp.unidades.qtd_consultorios IS
    'Denominador da taxa de ocupação: capacidade = consultorios * horas_uteis.';

-- -----------------------------------------------------------------------------
-- especialidades
-- -----------------------------------------------------------------------------
CREATE TABLE erp.especialidades (
    especialidade_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_especialidade  VARCHAR(10)  NOT NULL UNIQUE,
    nome_especialidade    VARCHAR(80)  NOT NULL,
    area                  VARCHAR(20)  NOT NULL
        CHECK (area IN ('Clínica', 'Cirúrgica', 'Estética', 'Diagnóstico')),
    ativa                 BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE erp.especialidades IS 'Catálogo de especialidades médicas atendidas pela rede.';

-- -----------------------------------------------------------------------------
-- funcionarios
-- -----------------------------------------------------------------------------
CREATE TABLE erp.funcionarios (
    funcionario_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula          VARCHAR(12)  NOT NULL UNIQUE,
    nome_funcionario   VARCHAR(120) NOT NULL,
    cargo              VARCHAR(60)  NOT NULL,
    departamento       VARCHAR(30)  NOT NULL
        CHECK (departamento IN ('Comercial', 'Atendimento', 'Financeiro',
                                'Marketing', 'Operações', 'Gestão')),
    unidade_id         BIGINT       NOT NULL REFERENCES erp.unidades (unidade_id),
    email_corporativo  VARCHAR(150) NOT NULL UNIQUE,
    data_admissao      DATE         NOT NULL,
    data_desligamento  DATE         NULL,
    ativo              BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_funcionarios_desligamento
        CHECK (data_desligamento IS NULL OR data_desligamento >= data_admissao)
);

COMMENT ON TABLE  erp.funcionarios IS
    'Colaboradores. Consultores comerciais saem daqui (departamento = Comercial).';
COMMENT ON COLUMN erp.funcionarios.data_desligamento IS
    'Preenchida no desligamento; a linha NÃO é deletada. O dashboard de performance de '
    'consultor precisa do funcionário desligado para não perder a receita histórica dele.';

-- -----------------------------------------------------------------------------
-- medicos
-- -----------------------------------------------------------------------------
CREATE TABLE erp.medicos (
    medico_id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crm                        VARCHAR(10)  NOT NULL,
    crm_uf                     erp.uf_br    NOT NULL,
    nome_medico                VARCHAR(120) NOT NULL,
    especialidade_principal_id BIGINT       NOT NULL
        REFERENCES erp.especialidades (especialidade_id),
    tipo_vinculo               VARCHAR(20)  NOT NULL
        CHECK (tipo_vinculo IN ('CLT', 'PJ', 'Parceiro')),
    percentual_repasse         erp.percentual NOT NULL,
    data_inicio_atuacao        DATE         NOT NULL,
    ativo                      BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Chave natural COMPOSTA: o CRM só é único dentro do estado emissor.
    -- 12345/SP e 12345/RJ são dois médicos diferentes.
    CONSTRAINT uq_medicos_crm UNIQUE (crm, crm_uf)
);

COMMENT ON TABLE  erp.medicos IS 'Corpo clínico da rede.';
COMMENT ON CONSTRAINT uq_medicos_crm ON erp.medicos IS
    'Chave natural composta. Deduplicar médico no DW por CRM sozinho gera colisão entre UFs.';

-- -----------------------------------------------------------------------------
-- medico_especialidade  (N:N)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.medico_especialidade (
    medico_id          BIGINT      NOT NULL REFERENCES erp.medicos (medico_id),
    especialidade_id   BIGINT      NOT NULL REFERENCES erp.especialidades (especialidade_id),
    data_certificacao  DATE        NOT NULL,
    principal          BOOLEAN     NOT NULL DEFAULT FALSE,
    criado_em          TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (medico_id, especialidade_id)
);

COMMENT ON TABLE erp.medico_especialidade IS
    'N:N. Um médico pode ter mais de um título. Contar "médicos por especialidade" '
    'somando esta tabela infla o total de médicos — precisa de tratamento no DW.';

-- -----------------------------------------------------------------------------
-- medico_unidade  (N:N COM VIGÊNCIA — SCD Tipo 2 já na origem)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.medico_unidade (
    medico_id              BIGINT      NOT NULL REFERENCES erp.medicos (medico_id),
    unidade_id             BIGINT      NOT NULL REFERENCES erp.unidades (unidade_id),
    data_inicio            DATE        NOT NULL,
    data_fim               DATE        NULL,
    carga_horaria_semanal  SMALLINT    NOT NULL CHECK (carga_horaria_semanal BETWEEN 1 AND 60),
    criado_em              TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em          TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- A data_inicio faz parte da PK: o mesmo médico pode voltar para a mesma
    -- unidade depois de um período fora, e isso são duas linhas legítimas.
    PRIMARY KEY (medico_id, unidade_id, data_inicio),

    CONSTRAINT ck_medico_unidade_vigencia
        CHECK (data_fim IS NULL OR data_fim > data_inicio)
);

COMMENT ON TABLE erp.medico_unidade IS
    'Vínculo médico↔unidade com vigência. É um SCD Tipo 2 nativo da origem: '
    'atribuir a receita de janeiro à unidade atual do médico reescreve o histórico.';

-- -----------------------------------------------------------------------------
-- convenios
-- -----------------------------------------------------------------------------
CREATE TABLE erp.convenios (
    convenio_id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_convenio      VARCHAR(10)  NOT NULL UNIQUE,
    nome_convenio        VARCHAR(100) NOT NULL,
    tipo_convenio        VARCHAR(20)  NOT NULL
        CHECK (tipo_convenio IN ('Saúde', 'Odontológico', 'Corporativo')),
    percentual_desconto  erp.percentual NOT NULL,
    prazo_repasse_dias   SMALLINT     NOT NULL CHECK (prazo_repasse_dias >= 0),
    ativo                BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE erp.convenios IS
    'Operadoras conveniadas. Atendimento particular é ausência de convênio (FK nula), '
    'não um registro "Particular" — decisão que força tratamento de NULL no DW.';
