-- =============================================================================
-- 03_crm.sql — Marketing e funil comercial
-- =============================================================================
-- Domínio de maior volume do banco. Contém as duas tabelas append-only de alta
-- cardinalidade (oportunidade_historico_etapa e atividades_crm), que exigem
-- estratégia de ingestão diferente das tabelas mutáveis do resto do modelo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- campanhas
-- -----------------------------------------------------------------------------
CREATE TABLE erp.campanhas (
    campanha_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_campanha    VARCHAR(20)  NOT NULL UNIQUE,
    nome_campanha      VARCHAR(150) NOT NULL,
    canal              VARCHAR(30)  NOT NULL
        CHECK (canal IN ('Google Ads', 'Meta Ads', 'TikTok Ads', 'E-mail',
                         'Outdoor', 'Rádio', 'Indicação', 'Parceria')),
    tipo_campanha      VARCHAR(20)  NOT NULL
        CHECK (tipo_campanha IN ('Aquisição', 'Retenção', 'Reativação', 'Institucional')),
    unidade_id         BIGINT       NULL REFERENCES erp.unidades (unidade_id),
    especialidade_id   BIGINT       NULL REFERENCES erp.especialidades (especialidade_id),
    data_inicio        DATE         NOT NULL,
    data_fim           DATE         NULL,
    orcamento_previsto erp.valor_monetario NOT NULL,
    custo_realizado    erp.valor_monetario NULL,
    status_campanha    VARCHAR(20)  NOT NULL DEFAULT 'Planejada'
        CHECK (status_campanha IN ('Planejada', 'Ativa', 'Pausada', 'Encerrada', 'Cancelada')),
    criado_em          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_campanhas_periodo CHECK (data_fim IS NULL OR data_fim >= data_inicio)
);

COMMENT ON TABLE  erp.campanhas IS 'Ações de marketing que originam leads.';
COMMENT ON COLUMN erp.campanhas.unidade_id IS
    'NULL = campanha nacional. Granularidade mista na mesma tabela: parte das linhas '
    'é de unidade, parte é da rede. Ratear custo nacional por unidade é decisão de DW.';
COMMENT ON COLUMN erp.campanhas.custo_realizado IS
    'Só é fechado no encerramento da campanha. Campanha ativa tem custo NULL — '
    'ROI calculado sobre ela é parcial por definição.';

-- -----------------------------------------------------------------------------
-- leads
-- -----------------------------------------------------------------------------
CREATE TABLE erp.leads (
    lead_id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campanha_id                BIGINT       NULL REFERENCES erp.campanhas (campanha_id),
    nome_lead                  VARCHAR(120) NOT NULL,
    email                      VARCHAR(150) NULL,
    telefone                   VARCHAR(20)  NOT NULL,
    cidade                     VARCHAR(80)  NULL,
    uf                         erp.uf_br    NULL,
    origem                     VARCHAR(30)  NOT NULL,
    unidade_interesse_id       BIGINT       NULL REFERENCES erp.unidades (unidade_id),
    especialidade_interesse_id BIGINT       NULL REFERENCES erp.especialidades (especialidade_id),
    data_captura               TIMESTAMPTZ  NOT NULL,
    status_lead                VARCHAR(20)  NOT NULL DEFAULT 'Novo'
        CHECK (status_lead IN ('Novo', 'Em contato', 'Qualificado',
                               'Desqualificado', 'Convertido')),
    motivo_desqualificacao     VARCHAR(60)  NULL,
    criado_em                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em              TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  erp.leads IS 'Contatos captados antes de virarem pacientes.';
COMMENT ON COLUMN erp.leads.campanha_id IS
    'NULL = lead orgânico (walk-in, indicação espontânea, busca direta). '
    'Primeiro elo do caminho de atribuição de receita — e o primeiro que quebra.';
COMMENT ON COLUMN erp.leads.email IS
    'Opcional de verdade: captação por telefone no balcão não coleta e-mail. '
    'Dedupe de lead por e-mail perde essa fatia.';

-- -----------------------------------------------------------------------------
-- etapas_funil
-- -----------------------------------------------------------------------------
CREATE TABLE erp.etapas_funil (
    etapa_id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_etapa             SMALLINT    NOT NULL UNIQUE,
    nome_etapa              VARCHAR(40) NOT NULL UNIQUE,
    tipo_etapa              VARCHAR(10) NOT NULL
        CHECK (tipo_etapa IN ('Aberta', 'Ganha', 'Perdida')),
    probabilidade_conversao erp.percentual NOT NULL,
    criado_em               TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE erp.etapas_funil IS
    'Dimensão de etapa do funil. `ordem_etapa` é o que permite calcular avanço vs '
    'retrocesso no histórico — sem ela, mudança de etapa é só um par de strings.';

-- -----------------------------------------------------------------------------
-- oportunidades
-- -----------------------------------------------------------------------------
CREATE TABLE erp.oportunidades (
    oportunidade_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_oportunidade VARCHAR(20) NOT NULL UNIQUE,
    lead_id           BIGINT       NULL REFERENCES erp.leads (lead_id),
    paciente_id       BIGINT       NULL,  -- FK adicionada em 04 (dependência circular)
    unidade_id        BIGINT       NOT NULL REFERENCES erp.unidades (unidade_id),
    consultor_id      BIGINT       NOT NULL REFERENCES erp.funcionarios (funcionario_id),
    etapa_atual_id    BIGINT       NOT NULL REFERENCES erp.etapas_funil (etapa_id),
    valor_estimado    erp.valor_monetario NOT NULL,
    data_abertura     TIMESTAMPTZ  NOT NULL,
    data_fechamento   TIMESTAMPTZ  NULL,
    status_oportunidade VARCHAR(10) NOT NULL DEFAULT 'Aberta'
        CHECK (status_oportunidade IN ('Aberta', 'Ganha', 'Perdida')),
    motivo_perda      VARCHAR(60)  NULL,
    criado_em         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_oportunidades_fechamento
        CHECK (data_fechamento IS NULL OR data_fechamento >= data_abertura),
    -- Oportunidade fechada obriga data de fechamento. Oportunidade aberta não pode ter.
    CONSTRAINT ck_oportunidades_coerencia_status
        CHECK (
            (status_oportunidade = 'Aberta'  AND data_fechamento IS NULL)
         OR (status_oportunidade <> 'Aberta' AND data_fechamento IS NOT NULL)
        )
);

COMMENT ON TABLE  erp.oportunidades IS 'Negociação comercial conduzida por um consultor.';
COMMENT ON COLUMN erp.oportunidades.lead_id IS
    'NULL = oportunidade nascida no balcão, sem passar por marketing. '
    'Um mesmo lead pode gerar várias oportunidades ao longo do tempo (recompra).';
COMMENT ON COLUMN erp.oportunidades.etapa_atual_id IS
    'Estado ATUAL, sobrescrito a cada avanço. O caminho percorrido só existe em '
    'oportunidade_historico_etapa — se a ingestão perder um dia, o trajeto some.';
COMMENT ON CONSTRAINT ck_oportunidades_coerencia_status ON erp.oportunidades IS
    'Invariante de negócio garantida na origem: o pipeline pode confiar nela e não '
    'precisa de teste dbt redundante para esse par de colunas.';

-- -----------------------------------------------------------------------------
-- oportunidade_historico_etapa  (APPEND-ONLY)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.oportunidade_historico_etapa (
    historico_id     BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id  BIGINT      NOT NULL REFERENCES erp.oportunidades (oportunidade_id),
    etapa_origem_id  BIGINT      NULL REFERENCES erp.etapas_funil (etapa_id),
    etapa_destino_id BIGINT      NOT NULL REFERENCES erp.etapas_funil (etapa_id),
    funcionario_id   BIGINT      NOT NULL REFERENCES erp.funcionarios (funcionario_id),
    data_mudanca     TIMESTAMPTZ NOT NULL,
    criado_em        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE erp.oportunidade_historico_etapa IS
    'Log imutável de transição de etapa. Nunca sofre UPDATE nem DELETE: ingestão é '
    'append puro por watermark de criado_em, sem MERGE. É a fonte de "tempo médio '
    'por etapa" e "conversão etapa a etapa".';
COMMENT ON COLUMN erp.oportunidade_historico_etapa.etapa_origem_id IS
    'NULL apenas no primeiro evento da oportunidade (entrada no funil).';

-- -----------------------------------------------------------------------------
-- atividades_crm  (APPEND-ONLY, maior tabela do banco)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.atividades_crm (
    atividade_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id  BIGINT       NULL REFERENCES erp.oportunidades (oportunidade_id),
    lead_id          BIGINT       NULL REFERENCES erp.leads (lead_id),
    funcionario_id   BIGINT       NOT NULL REFERENCES erp.funcionarios (funcionario_id),
    tipo_atividade   VARCHAR(20)  NOT NULL
        CHECK (tipo_atividade IN ('Ligação', 'WhatsApp', 'E-mail', 'Reunião',
                                  'Visita', 'Follow-up', 'Proposta enviada')),
    resultado        VARCHAR(20)  NOT NULL
        CHECK (resultado IN ('Sucesso', 'Sem resposta', 'Reagendado',
                             'Recusado', 'Caixa postal')),
    data_atividade   TIMESTAMPTZ  NOT NULL,
    duracao_minutos  SMALLINT     NULL CHECK (duracao_minutos IS NULL OR duracao_minutos >= 0),
    observacao       VARCHAR(255) NULL,
    criado_em        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Pai polimórfico: a atividade pertence a um lead OU a uma oportunidade.
    CONSTRAINT ck_atividades_vinculo
        CHECK (oportunidade_id IS NOT NULL OR lead_id IS NOT NULL)
);

COMMENT ON TABLE  erp.atividades_crm IS
    'Toque comercial registrado pelo consultor. Append-only e de maior cardinalidade '
    'do modelo (ordem de 500k): é a tabela que justifica particionamento no lake.';
COMMENT ON CONSTRAINT ck_atividades_vinculo ON erp.atividades_crm IS
    'Vínculo polimórfico. No DW cada linha precisa resolver para uma chave só — '
    'atividade de lead ainda não convertido não tem oportunidade para se pendurar.';
