-- =============================================================================
-- 04_pacientes_atendimento.sql — Cadastro de pacientes, agenda e clínico
-- =============================================================================
-- Aqui moram as tabelas que sofrem UPDATE de verdade (pacientes, agendamentos).
-- São elas que obrigam o pipeline a implementar MERGE em vez de append.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- pacientes
-- -----------------------------------------------------------------------------
CREATE TABLE erp.pacientes (
    paciente_id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_paciente       VARCHAR(15)  NOT NULL UNIQUE,
    lead_id               BIGINT       NULL REFERENCES erp.leads (lead_id),
    nome_paciente         VARCHAR(120) NOT NULL,
    cpf                   VARCHAR(14)  NOT NULL UNIQUE,
    data_nascimento       DATE         NOT NULL,
    sexo                  CHAR(1)      NOT NULL CHECK (sexo IN ('M', 'F', 'O')),
    email                 VARCHAR(150) NULL,
    telefone              VARCHAR(20)  NOT NULL,
    telefone_secundario   VARCHAR(20)  NULL,
    cep                   VARCHAR(9)   NULL,
    logradouro            VARCHAR(150) NULL,
    numero                VARCHAR(10)  NULL,
    complemento           VARCHAR(60)  NULL,
    bairro                VARCHAR(80)  NULL,
    cidade                VARCHAR(80)  NULL,
    uf                    erp.uf_br    NULL,
    unidade_cadastro_id   BIGINT       NOT NULL REFERENCES erp.unidades (unidade_id),
    data_primeiro_contato DATE         NOT NULL,
    ativo                 BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  erp.pacientes IS
    'Cadastro mestre de pacientes. Tabela mutável: contato e endereço mudam com o '
    'tempo e o ERP sobrescreve em cima. Carga incremental por atualizado_em + MERGE.';
COMMENT ON COLUMN erp.pacientes.lead_id IS
    'NULL quando o paciente chegou direto na recepção, sem passar por marketing. '
    'Quebra o caminho de atribuição orçamento→oportunidade→lead→campanha.';
COMMENT ON COLUMN erp.pacientes.atualizado_em IS
    'Watermark de CDC. Como o ERP sobrescreve o valor antigo, o histórico de telefone '
    'só existe se o pipeline materializar SCD Tipo 2 no Warehouse.';

-- FK adiada de oportunidades → pacientes (declarada aqui por dependência circular:
-- oportunidade referencia paciente, e paciente referencia lead, que precede ambos).
ALTER TABLE erp.oportunidades
    ADD CONSTRAINT fk_oportunidades_paciente
    FOREIGN KEY (paciente_id) REFERENCES erp.pacientes (paciente_id);

-- -----------------------------------------------------------------------------
-- paciente_convenio  (N:N COM VIGÊNCIA)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.paciente_convenio (
    paciente_id         BIGINT      NOT NULL REFERENCES erp.pacientes (paciente_id),
    convenio_id         BIGINT      NOT NULL REFERENCES erp.convenios (convenio_id),
    data_inicio         DATE        NOT NULL,
    data_fim            DATE        NULL,
    numero_carteirinha  VARCHAR(30) NOT NULL,
    titular             BOOLEAN     NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (paciente_id, convenio_id, data_inicio),

    CONSTRAINT ck_paciente_convenio_vigencia
        CHECK (data_fim IS NULL OR data_fim > data_inicio)
);

COMMENT ON TABLE erp.paciente_convenio IS
    'N:N com vigência: o paciente pode ter mais de um plano ativo e trocar de plano. '
    'Descobrir "qual convênio valia na data da consulta" é join por intervalo, não por igualdade.';

-- -----------------------------------------------------------------------------
-- agendamentos
-- -----------------------------------------------------------------------------
CREATE TABLE erp.agendamentos (
    agendamento_id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id            BIGINT       NOT NULL REFERENCES erp.pacientes (paciente_id),
    medico_id              BIGINT       NOT NULL REFERENCES erp.medicos (medico_id),
    unidade_id             BIGINT       NOT NULL REFERENCES erp.unidades (unidade_id),
    especialidade_id       BIGINT       NOT NULL REFERENCES erp.especialidades (especialidade_id),
    convenio_id            BIGINT       NULL REFERENCES erp.convenios (convenio_id),
    agendamento_origem_id  BIGINT       NULL REFERENCES erp.agendamentos (agendamento_id),
    funcionario_agendou_id BIGINT       NULL REFERENCES erp.funcionarios (funcionario_id),
    data_hora_agendada     TIMESTAMPTZ  NOT NULL,
    duracao_prevista_min   SMALLINT     NOT NULL CHECK (duracao_prevista_min > 0),
    tipo_agendamento       VARCHAR(20)  NOT NULL
        CHECK (tipo_agendamento IN ('Primeira consulta', 'Retorno', 'Avaliação', 'Procedimento')),
    canal_agendamento      VARCHAR(20)  NOT NULL
        CHECK (canal_agendamento IN ('Telefone', 'WhatsApp', 'Site', 'Presencial', 'App')),
    status_agendamento     VARCHAR(15)  NOT NULL DEFAULT 'Agendado'
        CHECK (status_agendamento IN ('Agendado', 'Confirmado', 'Realizado',
                                      'Cancelado', 'Falta', 'Reagendado')),
    motivo_cancelamento    VARCHAR(60)  NULL,
    data_cancelamento      TIMESTAMPTZ  NULL,
    criado_em              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  erp.agendamentos IS
    'Intenção de atendimento (slot reservado). Separado de `consultas` de propósito: '
    'FALTA é agendamento sem consulta correspondente. Num modelo de tabela única com '
    'flag de status, "cancelou com antecedência" e "não apareceu" viram a mesma coisa.';
COMMENT ON COLUMN erp.agendamentos.agendamento_origem_id IS
    'Auto-referência de reagendamento: aponta para o slot anterior que foi remarcado. '
    'Uma cadeia de remarcações vira lista ligada — contar remarcações exige CTE recursiva.';
COMMENT ON COLUMN erp.agendamentos.convenio_id IS 'NULL = atendimento particular.';

-- -----------------------------------------------------------------------------
-- consultas  (1:0..1 com agendamento)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.consultas (
    consulta_id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id     BIGINT      NOT NULL UNIQUE REFERENCES erp.agendamentos (agendamento_id),
    paciente_id        BIGINT      NOT NULL REFERENCES erp.pacientes (paciente_id),
    medico_id          BIGINT      NOT NULL REFERENCES erp.medicos (medico_id),
    unidade_id         BIGINT      NOT NULL REFERENCES erp.unidades (unidade_id),
    data_hora_inicio   TIMESTAMPTZ NOT NULL,
    data_hora_fim      TIMESTAMPTZ NULL,
    tempo_espera_min   SMALLINT    NULL CHECK (tempo_espera_min IS NULL OR tempo_espera_min >= 0),
    houve_encaminhamento BOOLEAN   NOT NULL DEFAULT FALSE,
    criado_em          TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_consultas_duracao
        CHECK (data_hora_fim IS NULL OR data_hora_fim >= data_hora_inicio)
);

COMMENT ON TABLE  erp.consultas IS
    'Atendimento efetivamente realizado. O UNIQUE em agendamento_id é o que impõe '
    'a cardinalidade 1:0..1 no banco em vez de deixar para o teste de qualidade.';
COMMENT ON COLUMN erp.consultas.paciente_id IS
    'Denormalizado do agendamento — como o ERP faz na prática. Serve de caso real de '
    'validação de consistência entre tabelas no dbt (consulta.paciente = agendamento.paciente).';

-- -----------------------------------------------------------------------------
-- prontuarios
-- -----------------------------------------------------------------------------
CREATE TABLE erp.prontuarios (
    prontuario_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id          BIGINT       NULL UNIQUE REFERENCES erp.consultas (consulta_id),
    paciente_id          BIGINT       NOT NULL REFERENCES erp.pacientes (paciente_id),
    medico_id            BIGINT       NOT NULL REFERENCES erp.medicos (medico_id),
    especialidade_id     BIGINT       NOT NULL REFERENCES erp.especialidades (especialidade_id),
    data_registro        TIMESTAMPTZ  NOT NULL,
    cid10                VARCHAR(8)   NULL,
    queixa_principal     VARCHAR(255) NOT NULL,
    diagnostico          VARCHAR(255) NULL,
    conduta              VARCHAR(255) NULL,
    retorno_recomendado  BOOLEAN      NOT NULL DEFAULT FALSE,
    gerou_indicacao      BOOLEAN      NOT NULL DEFAULT FALSE,
    criado_em            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  erp.prontuarios IS
    'Registro clínico. Um paciente acumula vários ao longo da vida; é a entidade que '
    'origina indicação de procedimento e, por consequência, orçamento.';
COMMENT ON COLUMN erp.prontuarios.consulta_id IS
    'UNIQUE porém NULLABLE. Em PostgreSQL vários NULLs convivem sob UNIQUE, então isso '
    'significa: no máximo um prontuário por consulta, e prontuário avulso é permitido.';
COMMENT ON COLUMN erp.prontuarios.gerou_indicacao IS
    'Marca o prontuário que indicou procedimento — é dele que sai o orçamento.';
