-- =============================================================================
-- 05_comercial.sql — Catálogo de procedimentos e orçamentos
-- =============================================================================
-- Núcleo do modelo. Contém a bridge prontuario_orcamento (N:N) e as duas chaves
-- compostas naturais que forçam decisão de surrogate key no Warehouse.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- procedimentos
-- -----------------------------------------------------------------------------
CREATE TABLE erp.procedimentos (
    procedimento_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_procedimento  VARCHAR(15)  NOT NULL UNIQUE,
    nome_procedimento    VARCHAR(150) NOT NULL,
    especialidade_id     BIGINT       NOT NULL REFERENCES erp.especialidades (especialidade_id),
    categoria            VARCHAR(30)  NOT NULL
        CHECK (categoria IN ('Consulta', 'Exame', 'Cirúrgico', 'Estético',
                             'Terapêutico', 'Preventivo')),
    valor_tabela         erp.valor_monetario NOT NULL,
    custo_estimado       erp.valor_monetario NOT NULL,
    duracao_media_min    SMALLINT     NOT NULL CHECK (duracao_media_min > 0),
    exige_retorno        BOOLEAN      NOT NULL DEFAULT FALSE,
    ativo                BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  erp.procedimentos IS 'Catálogo de serviços vendáveis.';
COMMENT ON COLUMN erp.procedimentos.valor_tabela IS
    'Preço de tabela VIGENTE, sobrescrito em reajuste. O preço praticado na venda fica '
    'congelado em orcamento_itens.valor_unitario — nunca reprecificar histórico por join aqui.';

-- -----------------------------------------------------------------------------
-- orcamentos
-- -----------------------------------------------------------------------------
CREATE TABLE erp.orcamentos (
    orcamento_id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orcamento       VARCHAR(20)  NOT NULL UNIQUE,
    paciente_id            BIGINT       NOT NULL REFERENCES erp.pacientes (paciente_id),
    unidade_id             BIGINT       NOT NULL REFERENCES erp.unidades (unidade_id),
    consultor_id           BIGINT       NOT NULL REFERENCES erp.funcionarios (funcionario_id),
    oportunidade_id        BIGINT       NULL REFERENCES erp.oportunidades (oportunidade_id),
    medico_responsavel_id  BIGINT       NULL REFERENCES erp.medicos (medico_id),
    convenio_id            BIGINT       NULL REFERENCES erp.convenios (convenio_id),
    data_emissao           TIMESTAMPTZ  NOT NULL,
    data_validade          DATE         NOT NULL,
    valor_bruto            erp.valor_monetario NOT NULL,
    valor_desconto         erp.valor_monetario NOT NULL DEFAULT 0,
    valor_liquido          erp.valor_monetario NOT NULL,
    percentual_desconto    erp.percentual NOT NULL DEFAULT 0,
    status_orcamento       VARCHAR(20)  NOT NULL DEFAULT 'Em elaboração'
        CHECK (status_orcamento IN ('Em elaboração', 'Enviado', 'Aprovado',
                                    'Recusado', 'Expirado', 'Cancelado')),
    data_aprovacao         TIMESTAMPTZ  NULL,
    motivo_recusa          VARCHAR(60)  NULL,
    qtd_parcelas           SMALLINT     NULL CHECK (qtd_parcelas BETWEEN 1 AND 12),
    forma_pagamento        VARCHAR(20)  NULL
        CHECK (forma_pagamento IN ('Dinheiro', 'PIX', 'Débito', 'Crédito',
                                   'Boleto', 'Convênio', 'Financiamento')),
    criado_em              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_orcamentos_valor_liquido
        CHECK (valor_liquido = valor_bruto - valor_desconto),
    -- Só orçamento aprovado tem data de aprovação e plano de parcelamento.
    CONSTRAINT ck_orcamentos_aprovacao
        CHECK (
            (status_orcamento = 'Aprovado' AND data_aprovacao IS NOT NULL AND qtd_parcelas IS NOT NULL)
         OR (status_orcamento <> 'Aprovado' AND data_aprovacao IS NULL)
        )
);

COMMENT ON TABLE  erp.orcamentos IS
    'Proposta comercial. Grão do fato de receita. Nem todo orçamento é aprovado — '
    'a taxa de aprovação é a métrica comercial central do negócio.';
COMMENT ON COLUMN erp.orcamentos.oportunidade_id IS
    'NULL quando o orçamento foi fechado direto no consultório sem passar pelo CRM. '
    'É o segundo ponto de quebra do caminho de atribuição de campanha.';
COMMENT ON COLUMN erp.orcamentos.qtd_parcelas IS
    'Entre 1 e 12. Redundante com COUNT(parcelas) de propósito: é assim que o ERP '
    'guarda, e divergência entre os dois é exatamente o teste de integridade do dbt.';
COMMENT ON CONSTRAINT ck_orcamentos_valor_liquido ON erp.orcamentos IS
    'Coluna derivada persistida. Mantida coerente na origem para que o pipeline possa '
    'reconciliar valor_liquido contra SUM(orcamento_itens.valor_total_item).';

-- -----------------------------------------------------------------------------
-- orcamento_itens  (CHAVE COMPOSTA)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.orcamento_itens (
    orcamento_id             BIGINT      NOT NULL REFERENCES erp.orcamentos (orcamento_id),
    item_seq                 SMALLINT    NOT NULL CHECK (item_seq > 0),
    procedimento_id          BIGINT      NOT NULL REFERENCES erp.procedimentos (procedimento_id),
    medico_executor_id       BIGINT      NULL REFERENCES erp.medicos (medico_id),
    quantidade               SMALLINT    NOT NULL CHECK (quantidade > 0),
    valor_unitario           erp.valor_monetario NOT NULL,
    percentual_desconto_item erp.percentual NOT NULL DEFAULT 0,
    valor_total_item         erp.valor_monetario NOT NULL,
    regiao_aplicacao         VARCHAR(40) NULL,
    status_item              VARCHAR(15) NOT NULL DEFAULT 'Previsto'
        CHECK (status_item IN ('Previsto', 'Executado', 'Cancelado')),
    data_execucao            TIMESTAMPTZ NULL,
    criado_em                TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em            TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Chave composta natural: a sequência é reiniciada dentro de cada orçamento.
    PRIMARY KEY (orcamento_id, item_seq),

    CONSTRAINT ck_orcamento_itens_execucao
        CHECK ((status_item = 'Executado') = (data_execucao IS NOT NULL))
);

COMMENT ON TABLE  erp.orcamento_itens IS
    'N:N entre orçamento e procedimento, com atributos próprios (preço praticado, '
    'desconto, executor). Grão diferente do orçamento: é a fonte de "receita por procedimento".';
COMMENT ON COLUMN erp.orcamento_itens.item_seq IS
    'Sequência local ao orçamento (1, 2, 3...). Sozinha não identifica nada — é meia chave.';
COMMENT ON COLUMN erp.orcamento_itens.medico_executor_id IS
    'Pode diferir do medico_responsavel_id do orçamento: quem indicou nem sempre executa. '
    'Atribuir receita por médico exige escolher qual dos dois papéis conta.';

-- -----------------------------------------------------------------------------
-- prontuario_orcamento  (BRIDGE N:N com fator de alocação)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.prontuario_orcamento (
    prontuario_id           BIGINT      NOT NULL REFERENCES erp.prontuarios (prontuario_id),
    orcamento_id            BIGINT      NOT NULL REFERENCES erp.orcamentos (orcamento_id),
    percentual_participacao erp.percentual NOT NULL,
    criado_em               TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (prontuario_id, orcamento_id)
);

COMMENT ON TABLE erp.prontuario_orcamento IS
    'BRIDGE. Um orçamento pode consolidar indicações de vários prontuários (e portanto '
    'de vários médicos e especialidades); um prontuário pode ser orçado em partes, em '
    'orçamentos distintos. Ligar fato_orcamento a dim_medico por aqui SEM ponderar '
    'multiplica a receita pelo número de prontuários envolvidos.';
COMMENT ON COLUMN erp.prontuario_orcamento.percentual_participacao IS
    'Fator de alocação. Soma 100 dentro de cada orcamento_id. Aplicar em métrica '
    'atribuída (receita por médico) e IGNORAR em métrica total (receita da unidade) — '
    'usar o fator nos dois casos subestima o faturamento.';

-- -----------------------------------------------------------------------------
-- orcamento_historico_status  (APPEND-ONLY)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.orcamento_historico_status (
    historico_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id     BIGINT       NOT NULL REFERENCES erp.orcamentos (orcamento_id),
    status_anterior  VARCHAR(20)  NULL,
    status_novo      VARCHAR(20)  NOT NULL,
    funcionario_id   BIGINT       NULL REFERENCES erp.funcionarios (funcionario_id),
    data_mudanca     TIMESTAMPTZ  NOT NULL,
    observacao       VARCHAR(255) NULL,
    criado_em        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE erp.orcamento_historico_status IS
    'Log imutável do ciclo de vida do orçamento. Permite reconstruir a foto do funil '
    'em qualquer data passada — algo impossível só com o status atual em `orcamentos`.';
