-- =============================================================================
-- 06_financeiro.sql — Parcelamento e recebimento
-- =============================================================================
-- Ramo irmão de orcamento_itens: ambos penduram no orçamento, em grãos distintos.
-- Juntar os dois na mesma query é o fan trap clássico do modelo.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- parcelas  (CHAVE COMPOSTA)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.parcelas (
    orcamento_id             BIGINT      NOT NULL REFERENCES erp.orcamentos (orcamento_id),
    numero_parcela           SMALLINT    NOT NULL CHECK (numero_parcela BETWEEN 1 AND 12),
    valor_parcela            erp.valor_monetario NOT NULL,
    data_vencimento          DATE        NOT NULL,
    status_parcela           VARCHAR(15) NOT NULL DEFAULT 'Aberta'
        CHECK (status_parcela IN ('Aberta', 'Paga', 'Parcial', 'Vencida',
                                  'Cancelada', 'Renegociada')),
    valor_pago               erp.valor_monetario NOT NULL DEFAULT 0,
    data_ultimo_pagamento    DATE        NULL,
    forma_pagamento_prevista VARCHAR(20) NULL,
    criado_em                TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em            TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (orcamento_id, numero_parcela)
);

COMMENT ON TABLE  erp.parcelas IS
    'Plano de pagamento do orçamento aprovado (1 a 12x). Tabela mutável: muda de status '
    'a cada recebimento e a cada virada de vencimento. É a fonte de inadimplência.';
COMMENT ON COLUMN erp.parcelas.status_parcela IS
    'Vencida é status DERIVADO do tempo, não de um evento: a parcela vira "Vencida" '
    'sozinha quando a data passa e nada foi pago. Quem faz o UPDATE é uma rotina em '
    'lote do ERP, sem ação de usuário — o que produz dias com milhares de linhas '
    'alteradas de uma vez. O pipeline precisa aguentar o pior dia, não o dia médio.';
COMMENT ON COLUMN erp.parcelas.valor_pago IS
    'Acumulado dos pagamentos. Menor que valor_parcela = status Parcial.';

-- -----------------------------------------------------------------------------
-- pagamentos  (APPEND-ONLY, FK COMPOSTA)
-- -----------------------------------------------------------------------------
CREATE TABLE erp.pagamentos (
    pagamento_id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id            BIGINT      NOT NULL,
    numero_parcela          SMALLINT    NOT NULL,
    unidade_recebimento_id  BIGINT      NOT NULL REFERENCES erp.unidades (unidade_id),
    valor_pago              erp.valor_monetario NOT NULL CHECK (valor_pago > 0),
    data_pagamento          TIMESTAMPTZ NOT NULL,
    forma_pagamento         VARCHAR(20) NOT NULL
        CHECK (forma_pagamento IN ('Dinheiro', 'PIX', 'Débito', 'Crédito',
                                   'Boleto', 'Convênio', 'Financiamento')),
    bandeira_cartao         VARCHAR(20) NULL,
    codigo_autorizacao      VARCHAR(30) NULL,
    estornado               BOOLEAN     NOT NULL DEFAULT FALSE,
    data_estorno            TIMESTAMPTZ NULL,
    criado_em               TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- FK COMPOSTA apontando para a PK composta de parcelas.
    CONSTRAINT fk_pagamentos_parcela
        FOREIGN KEY (orcamento_id, numero_parcela)
        REFERENCES erp.parcelas (orcamento_id, numero_parcela),

    CONSTRAINT ck_pagamentos_estorno
        CHECK ((estornado = TRUE) = (data_estorno IS NOT NULL))
);

COMMENT ON TABLE  erp.pagamentos IS
    'Evento de recebimento. Uma parcela pode receber N pagamentos (pagamento parcial, '
    'entrada + complemento). Append-only: estorno é uma flag na linha, nunca um DELETE.';
COMMENT ON CONSTRAINT fk_pagamentos_parcela ON erp.pagamentos IS
    'FK composta. No Warehouse a fato de pagamento precisa da mesma dupla de colunas '
    'para achar a parcela, ou de uma surrogate key criada na silver.';
COMMENT ON COLUMN erp.pagamentos.unidade_recebimento_id IS
    'A unidade que RECEBEU pode não ser a que vendeu — paciente paga em qualquer clínica '
    'da rede. Receita "por unidade" muda de resposta conforme o papel escolhido.';
COMMENT ON COLUMN erp.pagamentos.estornado IS
    'Pagamento estornado continua na tabela. Somar valor_pago sem filtrar estorno infla '
    'o caixa — erro que só aparece na conciliação.';
